### ISSUE TITLE
Add privacy settings

### ISSUE THREAD

**Issue by shc261392** [numbersprotocol/capture-lite#119]
## Concept

**! Need feature clarification**

If we provide \[feature]

## Reason/Hypothesis

We can help \[who] to \[benefit] or solve \[problem] because we know \[who] are \[faced about our target].

## More Description (if any)

Put more description here to support the concept.

## Suggested Implementation (if any)

Put some suggested implementation here if you already have some ideas in mind.

**Comment by shc261392** [comment]
Pending until get updates from #121

**Comment by scott-dt** [comment]
201013 postpone 到下個 milestone

**Comment by seanwu1105** [comment]
Fixed with 619ad984542720cccee932288ad604826394118d.
