### ISSUE TITLE
UX for privacy settings

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#121]
(WIP)

## Update Purpose

Write the purpose of UI update here.

![css](https://media.giphy.com/media/yYSSBtDgbbRzq/giphy.gif)

## UI Suggestion

Put images or link to the contents of suggestions.

## More Description (if any)

Put more description here to help developers understand.

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/95079154-d22aeb80-0748-11eb-9d5c-6d50949bdcf9.png)

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/95080702-13bc9600-074b-11eb-8b72-0be381afd941.png)
![image](https://user-images.githubusercontent.com/16307922/95080776-2e8f0a80-074b-11eb-87f8-52720872a800.png)
可以參考這幾方案

這個是比較貼近原生
![image](https://user-images.githubusercontent.com/16307922/95080876-4ebec980-074b-11eb-95d8-0fb4c53c5916.png)

**Comment by CS6** [comment]
icon 已經放在 `src/assets/appicon`
![image](https://user-images.githubusercontent.com/16307922/95164321-5c705f80-07dc-11eb-8760-c3b5e9bea742.png)
![image](https://user-images.githubusercontent.com/16307922/95164691-06e88280-07dd-11eb-8e62-87c2d09ab673.png)

https://www.figma.com/file/XW6PCABaxTBxKlCAqH95W9/?node-id=399%3A990

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/95309819-34f1c380-08be-11eb-8d50-6935eca58bb1.png)

D94C4C => 4C4C4C
