### ISSUE TITLE
Prepare terms & condition agreements for launching App

### ISSUE THREAD

**Issue by shc261392** [numbersprotocol/capture-lite#136]

**Comment by seanwu1105** [comment]
![Screenshot from 2020-11-09 16-50-18](https://user-images.githubusercontent.com/14951000/98519403-b072d600-22ab-11eb-8d7c-a19401a151f8.png)

Policy: https://drive.google.com/drive/folders/1_7MlAZa9_uA-pG0Bn1raZRRffVMrHB_G?usp=sharing
