### ISSUE TITLE
Capture Wall

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#141]
Implement the UI for Capture/Post Capture Wall.

![Screenshot from 2020-10-29 12-15-18](https://user-images.githubusercontent.com/14951000/97524789-6ef74680-19e0-11eb-9cb4-f001077f82f9.png)

![Screenshot from 2020-10-29 12-26-34](https://user-images.githubusercontent.com/14951000/97525551-08732800-19e2-11eb-8df5-c3d77f1cd6e2.png)

**Comment by scott-dt** [comment]
請見 https://docs.google.com/presentation/d/1lnXs-dMzKT7IiAce4GdE9KLxohg2SFAWdlb-x0yaxtE/edit?usp=sharing

**Comment by scott-dt** [comment]
v0.7.2 修正完成
