### ISSUE TITLE
Capture Details

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#142]
Implement the UI for Capture Details.

![Screenshot from 2020-10-29 12-14-14](https://user-images.githubusercontent.com/14951000/97524713-4c652d80-19e0-11eb-9065-b85616004bd8.png)

**Comment by scott-dt** [comment]
請見 https://docs.google.com/presentation/d/1lnXs-dMzKT7IiAce4GdE9KLxohg2SFAWdlb-x0yaxtE/edit?usp=sharing
