### ISSUE TITLE
Sending Post Capture UI

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#143]
Implement the UI for sending post capture.

![Screenshot from 2020-10-29 12-19-38](https://user-images.githubusercontent.com/14951000/97525082-08265d00-19e1-11eb-9ea3-1dea68ea6272.png)

**Comment by scott-dt** [comment]
請見 https://docs.google.com/presentation/d/1lnXs-dMzKT7IiAce4GdE9KLxohg2SFAWdlb-x0yaxtE/edit?usp=sharing
