### ISSUE TITLE
Activity (History) Page

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#145]
Implement activity (history) page.

![Screenshot from 2020-10-29 13-43-31](https://user-images.githubusercontent.com/14951000/97530284-c26f9180-19ec-11eb-8c41-74bd1e3a764d.png)

**Comment by scott-dt** [comment]
![Uploading Screenshot_20201112-183015.png…]()

**Comment by scott-dt** [comment]
![Screenshot_20201112-183015](https://user-images.githubusercontent.com/62582260/98928958-6b51dc80-2515-11eb-948b-db62de72d00a.png)
