### ISSUE TITLE
Inbox Page

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#146]
Implement inbox page.

![Screenshot from 2020-10-29 13-44-30](https://user-images.githubusercontent.com/14951000/97530351-e337e700-19ec-11eb-94af-8466d754217b.png)

**Comment by scott-dt** [comment]
![Screenshot_20201112-182548](https://user-images.githubusercontent.com/62582260/98928502-d0590280-2514-11eb-98c1-73ac78ee8b67.png)
