### ISSUE TITLE
Contacts Page

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#147]
Implement contacts page.

![Screenshot from 2020-10-29 14-32-52](https://user-images.githubusercontent.com/14951000/97533708-aae7d700-19f3-11eb-83ae-382523ebccab.png)

**Comment by scott-dt** [comment]
請見 https://docs.google.com/presentation/d/1lnXs-dMzKT7IiAce4GdE9KLxohg2SFAWdlb-x0yaxtE/edit?usp=sharing

**Comment by scott-dt** [comment]
v0.7.2 修正成為 slide 狀態
