### ISSUE TITLE
The options of settings have multiple arrow

### ISSUE THREAD

**Issue by wcchung** [numbersprotocol/capture-lite#161]
## Description

See image
![image](https://user-images.githubusercontent.com/12252921/97949431-9417fa80-1dce-11eb-9c05-6386e0091c86.png)

## Steps to Reproduce

1. Go to 'main page'
2. Click on 'Menu button'
3. See error

## Expected Behavior

* Expected: One option has one arrow.
* Actual: One option has multiple arrow.

## Logs

If applicable, add logs or screenshots to help explain your problem.

## Environment

* Version: v0.5.1
* OS: iOS 14.1
* Device: iPhone SE2

**Comment by keygen-maker** [comment]
Capture One Activation Key Pro 20 still maintains its broad set of editing and production features, including the ability to work with types of catalog or session organization, configurable and sortable keywords, support for over 500 individual cameras, metadata types and rich file types. Editing capabilities.
Karen
keygenbro.com

**Comment by khansa608** [comment]
Capture One Keygen software program has been developed with the goal of enabling innovators to achieve their goals. Through efficient and efficient workflow, Capture One is the professional choice of photography software. 
Brenda
patchhere.com

**Comment by scott-dt** [comment]
![File (2)](https://user-images.githubusercontent.com/62582260/98525353-4d853d00-22b3-11eb-842e-c869adf4832b.jpg)
