### ISSUE TITLE
Fix Warning: '%c Missing translation for 'en.XXX'', 'font-size: 12px; color: red'

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#162]
Fix the warnings `WARN: '%c Missing translation for 'en.signUp'', 'font-size: 12px; color: red'`. Most of the warnings come from `signup.page` and `login.page`. Thus, it is possible caused by `TranslocoModule`, `TranslocoService` and `FormlyModule`.

**Comment by seanwu1105** [comment]
This issue is fixed with abf3ff3bd86d4bda7683713adf0b2003da6c9519.

**Comment by faizaldong** [comment]
what did you fix actually? I had same issue
