### ISSUE TITLE
Connect to PostCapture APIs

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#169]
Implement the MVP to send, receive and view PostCaptures.

- [x] Send a PostCapture
  - [x] Confirm dialog before sending
- [x] Receive the PostCapture
- [x] View the PostCapture

**Comment by scott-dt** [comment]
接收 & 傳送 沒有問題但是  ignore 沒有反應 #184

**Comment by scott-dt** [comment]
ignore 沒有反應  於0.7.1 修正
