### ISSUE TITLE
拍攝照片位置資訊在卡片樣式時會為空白 但點入詳細資訊會顯示經緯度 

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#187]
## Description

拍攝照片位置資訊在卡片樣式時會為空白 但點入詳細資訊會顯示經緯度 

## Steps to Reproduce

1. 拍完照片 
2. 點選圖片
3. 位置顯示為空白
4. 點選檢視全部裡面有顯示經緯度

## Expected Behavior

* Expected: 需顯示一致
* Actual: 外面顯示空白裡面有資料的狀態

![Screenshot_20201112-192129](https://user-images.githubusercontent.com/62582260/98933963-54fb4f00-251c-11eb-9bdb-09620460516a.png)
![Screenshot_20201112-192133](https://user-images.githubusercontent.com/62582260/98933968-562c7c00-251c-11eb-952c-a4a10d643b78.png)

## Environment

* Version: 0.7.0
* OS:Android8.1.0 , Android 10
* Device:  HTC Exodus 1s , samsung note20

**Comment by seanwu1105** [comment]
@scott-dt Cannot reproduce. It seems the error does not always reproducible.

**Comment by scott-dt** [comment]
英文時可顯示 location 在 capture 頁面 ，但切換至中文就會顯示空白
