### ISSUE TITLE
目前 app 照片都會存在 local，尚未與 cloud sync，後續與 edge hash 機制一起做

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#189]
## Concept

If we provide \[feature]

## Reason/Hypothesis

We can help \[who] to \[benefit] or solve \[problem] because we know \[who] are \[faced about our target].

## More Description (if any)

Put more description here to support the concept.

## Suggested Implementation (if any)

Put some suggested implementation here if you already have some ideas in mind.

**Comment by tammyyang** [comment]
FR changed, closed
