### ISSUE TITLE
inbox 按下接收後 會停頓約20~35秒 inbox 記錄才會消失，且 postcapture 顯示接收檔案。等待時間過長

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#191]

**Comment by wcchung** [comment]
已加入等待符號 workaround


Scott Yan  18:02
@Sean Wu #5 我有看到跳 plase wait 的等帶畫面 這項我這邊可以給通過 持續測試其他項目

**Comment by seanwu1105** [comment]
This can be addressed perfectly with #212 and #226. We should postpone this task to the future milestone if it is not critical after adding the "Please Wait" blocking dialog.

**Comment by scott-dt** [comment]
0.9.3 無法接收 所以沒有測過 但點即拒絕是正常消失
