### ISSUE TITLE
拍完照片後須等待 19s ~ 38s 才會出現在手機 Capture 頁面裡，等待時間過長

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#192]
## Description
不管是 ios 還是 android 測試時都有發現如果是連家用 wifi 約5~15s 可完成顯示在 capture 如果是使用手機本身 4G 網路 時間會拖到 30s 甚至以上的時間

Tammy  28 minutes ago
@Sean Wu 這是因為下載原圖的關係對吧? 如果是的話，之後想變成兩段
1. 先下載 thumbnail 顯示
2. 再下載原圖蓋掉

**Comment by seanwu1105** [comment]
1. CPU and Internet speed is the bottleneck of the publishing performance.
2. Storage can also be improved to reduce the publishing time.

**Comment by wcchung** [comment]
The issue had improve in 0.11.7 release. Keep monitoring in new release

**Comment by wcchung** [comment]
Due to other UX issue, revert back to 0.7.5. So this issue is still exist.

**Comment by wcchung** [comment]
Temporarily move to beta 8.2 (cc @scott-dt )
