### ISSUE TITLE
Can show different icon to distinguish different "In Progress" activity

### ISSUE THREAD

**Issue by wcchung** [numbersprotocol/capture-lite#199]
## Update Purpose

Can use different icon or color to distinguish "In Progress" - delivering & "In Progress" - waiting to receive

![image](https://user-images.githubusercontent.com/12252921/99065745-cd2c4800-25e2-11eb-90a5-49ae935e3afd.jpeg)

**Comment by scott-dt** [comment]
Tammy  6:18 PM
replied to a thread:
@Scott Yan @DaYuan (cc @Sean Wu) 已 comment，紅色表示要改回原本的 UI 設計實作，黃色表示有 comment，可部分改即可，綠色表示維持現狀。麻煩明天 EOD 再出一版
@Sean Wu 之前 @DaYuan 告知是會用用實心空心來區分
自己送出的 PostCapture（空心）
- In Progress
- Received
- Returned
別人送來的 PostCapture（實心）
- In Progress
- Accepted
（或是兩者空心實心調換亦可）
