### ISSUE TITLE
ios 目前無法接收 postcapture

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#203]
## Description
ios 目前無法接收 postcapture

**Comment by scott-dt** [comment]
0.7.5版本 ios 13.7 postcapture 接受後無法顯示 但 ios 14.1 可正常顯示

**Comment by scott-dt** [comment]
接收 postcapture  inbox 顯示有時候沒有顯示紅點 有時候又馬上可以顯示 沒顯示紅點按 activity 頁面裡面也沒有顯示應該等待接收的 postcapture

**Comment by wcchung** [comment]
App 滑掉重啟後即可解決，於 beta 7.4 修正。
