### ISSUE TITLE
刪除照片後 dashboard 上仍然存在 (需與 pm 討論)

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#210]
## Description
刪除照片後 dashboard 上仍然存在 是否需要收機刪除後 dashboard 跟著刪除

**Comment by wcchung** [comment]
@scott-dt 目前版本在 Capture App 上刪除照片，Authmedia 上應該也會刪除了。這個 issue 應該已經處理完畢

**Comment by scott-dt** [comment]
capture  beta 8  0.12.1  確認修正
