### ISSUE TITLE
Flow of the Capture upload

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#212]
目前 Capture 會等待 backend 回傳才將圖片存入
萬一網路不穩或很慢，使用者就會看不見 Capture 的照片、甚至掉了照片
需要更新與討論 Capture 從拍照到上傳以及續傳等 flow & UX

**Comment by seanwu1105** [comment]
The flow should include the local cache. See #226.

**Comment by tammyyang** [comment]
![Uploading Capture - 20.12.06 Photo capture flow.jpg…]()
