### ISSUE TITLE
postcapture 顯示圖片會一格一格慢慢向下顯示圖片

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#221]
## Description

postcapture 顯示圖片會一格一格慢慢向下顯示慢慢顯示成完整圖片
 samsung note20 Android 10 在 3 張以內可以直接顯示 超過 3張即會有此現象產生 (每張圖片皆是一格一格慢慢顯示出來變成完整圖片 )
iphon ios 14.1 無論相片張數皆會此現象

## Logs
![Screenshot_20201117-133237_Capture](https://user-images.githubusercontent.com/62582260/99350771-1e398600-28da-11eb-804b-74a6615d50a1.jpg)

## Environment

* Version: 0.7.5
* OS: Android 8.1.0, Android 10, iOS 14.1
* Device: HTC Exodus 1s, samsung note20 , iphone se

**Comment by wcchung** [comment]
@scott-dt This should be fixed in previous version? please confirm

**Comment by scott-dt** [comment]
0.12.0 已修正確認
