### ISSUE TITLE
Use Repository Pattern to Cache Internet Query

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#226]
Apply the repository pattern to the app to cache Internet data.

![repository](https://developer.android.com/topic/libraries/architecture/images/final-architecture.png)

**Comment by scott-dt** [comment]
201202 demo 會議提出將數字通知改為紅點通知

**Comment by seanwu1105** [comment]
`DiaBackendContactRepository` has adopted this design.
