### ISSUE TITLE
72 小時退回

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#229]
## Description

72 小時退回

**Comment by seanwu1105** [comment]
WORKAOUNRD: Store expired PostCapture with a very fragile method.

The current implementation only store the expired PostCapture on
a notification pushed. If a user does not open the app when the
PostCapture expired, the PostCapture will never get back.

See 4348bd5d431d3bf2a9dfc069ba2bf8a4817453ef.

**Comment by seanwu1105** [comment]
Currently, due to the limitation of Capacitor plugin and FCM, you cannot get the returned asset when app is not in the foreground. See #294.

**Comment by scott-dt** [comment]
beta7.3 進行測試

**Comment by scott-dt** [comment]
目前尚在等待 0.11.7 12/15 送出之結果
