### ISSUE TITLE
Update metadata dialogue view

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#23]
Concept
If we make the metadata dialogue view more user friendly

Reason/Hypothesis

We can help users understand what these metadata mean

**Comment by tammyyang** [comment]
![Starling Capture - UX Wireframes](https://user-images.githubusercontent.com/5687908/88827108-1c00ce00-d1fc-11ea-8ca3-84e55f667d5f.jpg)

**Comment by seanwu1105** [comment]
@ethanwu155 To implement the preview of the information, you might need to add two attributions to the Information schema: `groupId: int` and `importance: int`.

**Comment by seanwu1105** [comment]
@ethanwu155 

## Design Suggestion

To make the information card more user-friendly and well-organized, we could show only some important information on the proof page and provide another page (e.g. information page) to display all information collected. Take Starling Capture app for example,

|![Screenshot_20200806-105746](https://user-images.githubusercontent.com/14951000/89534176-1ec87800-d827-11ea-8ed8-2ef82ffe5ff6.png)|![Screenshot_20200806-105749](https://user-images.githubusercontent.com/14951000/89534232-330c7500-d827-11ea-96b3-3b2c43e1e654.png)|
|---|---|

## Implementation Suggestion

The following implementation is modified from the Starling Capture app.

- Add `importance` attribution to the `Information` interface and only show the important information on the proof page.
- Hardcode the `importance` when collecting the proof with the `CapacitorProvider` class.
- Create the information page to show all information from a specific proof with the given information provider.
- Add the "view all" button on the information card on the proof page. The button will link to the information page.
- Add `type` attribution to the `Information` interface and use it sort and display the "grouped" list on the information page.

The implementation mentioned above is just a suggestion :)

**Comment by ethanwu155** [comment]
<img width="292" alt="Screen Shot 2020-08-11 at 11 29 58 PM" src="https://user-images.githubusercontent.com/17772957/89916896-bb758600-dc2a-11ea-9ccb-7339f60a50a4.png"><img width="292" alt="Screen Shot 2020-08-11 at 11 30 11 PM" src="https://user-images.githubusercontent.com/17772957/89916911-bfa1a380-dc2a-11ea-8bcf-e2889177322d.png">

Thanks for your explanation and help with this task :)

**Comment by scott-dt** [comment]
20200825 Second confirmation by scott
