### ISSUE TITLE
替代方案來儲存檔案

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#232]
## Description
找個穩定且有在積極維護的替代方案來儲存檔案，但是這件事情需要至少半個 sprint，而且需要多方嘗試與實做試試看來比較，上次有跟 @James 討論過 RxDB 等等替代方案。目前最快的 workaround 是直接 catch 掉所有  Capacitor.Filesystem.deleteFile()  產生的錯誤訊息。但是這個解決方法很爛，而且只會讓未來越來越難 debug。

**Comment by seanwu1105** [comment]
Duplicate of #181. Move the discussion to that issue.
