### ISSUE TITLE
仿照 Instagram 的顯示方式，裁切照片以適當 size 顯示

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#235]
仿照 Instagram 的顯示方式，裁切照片以適當 size 顯示 (方、長；寬三個比例) - (但是我們的原始照片不更動，只在顯示上調整)

**Comment by CS6** [comment]
Instagram 照片分別支援
正方（比例1:1）建議尺寸為1080 x 1080px、
打直（比例4:5）建議尺寸為1080 x 1350px 
打橫（比例16:9）建議尺寸為1080 x 606px 
三個尺寸的帖文照片，如果上載不是最佳尺寸的話有可能出現照片被裁走或自動放大縮少並補上白邊的情況。
