### ISSUE TITLE
Add information provider toggle

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#24]
Concept
If we ass information-provider toggles in the preference

Reason/Hypothesis

User can choose to enable/disable the provider seperately

**Comment by tammyyang** [comment]
![Starling Capture - UX Wireframes](https://user-images.githubusercontent.com/5687908/88827698-dee90b80-d1fc-11ea-8639-8f8083513ebb.jpg)

**Comment by tammyyang** [comment]
![Starling Capture - UX Wireframes(2)](https://user-images.githubusercontent.com/5687908/88827754-f1634500-d1fc-11ea-8bd9-71a8b33e727f.jpg)

**Comment by tammyyang** [comment]
Postpone to next milestone. It makes more sense to implement this with on-boarding tutorials

**Comment by scott-dt** [comment]
因為目前還沒有onboarding 頁面 之後可能會有重工 目前可以先將 preference 先定義項目設定 同一頁新增 location 開關 詳細頁面架構請見 https://miro.com/app/board/o9J_koV7S2I=/ [20.08.03 kickoff minutes]

**Comment by scott-dt** [comment]
![Screenshot_20200820-132013](https://user-images.githubusercontent.com/62582260/90719987-44a25200-e2e8-11ea-9afb-dceb480277cb.png)

**Comment by scott-dt** [comment]
20200825 Second confirmation by scott
