### ISSUE TITLE
Bugs After UI Update (#255)

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#259]
- [x] 按鈕的 ripple effects 歪掉
- [x] 在 Capture Details 頁面的 View All 按鈕沒有順利的套用 `<div class="page-content">` 的 bottom padding，因此直接貼邊。你新增在 `button.center` 的 `top: 25%;  height: 50px;` 造成的，應該用一個 spacer with `flex-grow` 去達成按鈕置底。`height: 50px;` 和 Figma 上的設計不同。
- [x] Header title 應該要置中才符合 Figma 設計。
- [x] PostCapture 頁面無法捲動而且側邊出現不必要的 overflow 造成可以橫向捲動。
- [x] PostCapture 頁面載入後出現以下錯誤訊息：`Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'calc(100vw / 16 * 9)'. Current value: 'calc(100vw / 4 * 5)'.`

**Comment by scott-dt** [comment]
View All 按鈕沒有修正還是切一半

**Comment by CS6** [comment]
@scott-dt 可以提供截圖嗎？

**Comment by scott-dt** [comment]
![Screenshot_20201204-124322_Capture](https://user-images.githubusercontent.com/62582260/101138199-dab97880-364a-11eb-8b35-6893d9746346.jpg)

**Comment by scott-dt** [comment]
ios 是直接沒顯示

**Comment by CS6** [comment]
喔喔，這是被遮掉，跟 https://github.com/numbersprotocol/capture-lite/issues/282 是一樣的

**Comment by CS6** [comment]
fix 
![image](https://user-images.githubusercontent.com/16307922/101365148-63037c00-38de-11eb-8c2e-a93b56028ca9.png)

**Comment by scott-dt** [comment]
0.10.0 ios 尚未修復

**Comment by seanwu1105** [comment]
Superseded by #282.
