### ISSUE TITLE
Can upload data to dashboard

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#26]
## Concept

If we allow users to upload data to dashboard.

## Reason/Hypothesis

We can help users manage their own data and get the certificate.

## More Description (if any)

Put more description here to support the concept.

## Suggested Implementation (if any)

Put some suggested implementation here if you already have some ideas in mind.

**Comment by scott-dt** [comment]
![image](https://user-images.githubusercontent.com/62582260/91115150-28bdf800-e6bc-11ea-87b6-d4d1ba2484c0.png)

**Comment by scott-dt** [comment]
20200825 Second confirmation by scott
