### ISSUE TITLE
進行連續拍攝第一張相片遺失

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#266]
## Description

沒等前一張照片完全顯示於capture 還在收集資料發布時 馬上點選相機進行拍攝 會偶發式的發生第一張相片遺失
總共連續拍照5次 但capture 頁面只顯示 4張 連續測試10 次 發生一次 ( note20 )
總共連續拍照5次 但capture 頁面只顯示 4張 連續測試10 次 發生兩次 ( htc 1s )
目前尚未確認是否有固定步驟能造成此現象 ， 試過 以下兩種
1. 完全關閉 app 後連續拍攝 ( 5次 發生兩次 一次在not20 一次在 htc 1s )
2. app 已先正常拍攝並顯示 1 張後，在進行連續拍攝 ( 5次發生一次 在 htc 1s )
p.s : 0.7.5 版本也有回報發生此現象 在ios 14.1 / iphone 10 & Android 8.1.0 / htc 1s
## Steps to Reproduce

1.點選右下角 "相機 icon " 
2..進入相機模式
3.. 按下快門 
4.. 點選 " 確認 " 且 app 自動跳回 capture 頁面後 ( 這時候 app 還在收集資料跟發布 )
5. 接著步驟 2 ~ 5 連續5次

## Expected Behavior

* Expected: 正常顯示張數
* Actual: 第一章會有遺失沒有存下來的狀態

## Environment
* Version: 0.7.5 ,  0.8.1
* OS: Android 8.1.0/ Android 10 / ios14.1
* Device: HTC EXODUS 1s / samsung note20 / iphone 10

**Comment by seanwu1105** [comment]
@scott-dt It is possible that OS kills the Capture Lite app due to low memory caused by the external camera app. The beta 7.2 release should fix the problem by restoring the killed camera photo automatically.

**Comment by scott-dt** [comment]
v0.11.6 目前相片會在手機上紀錄顯示驚嘆號 目前連拍20 張皆沒有掉照片的狀況
