### ISSUE TITLE
Cannot Scroll on Asset Page

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#282]
Unable to scroll on asset page to click on "View All" button if the captured image is 9:16.

Environment: Exodus 1s. Android API26.

![Screenshot_20201202-172842](https://user-images.githubusercontent.com/14951000/100854875-87b5b900-34c4-11eb-8daf-504946ea5bfd.png)

**Comment by CS6** [comment]
fix 
![image](https://user-images.githubusercontent.com/16307922/101365383-afe75280-38de-11eb-940b-5c16270b2742.png)

**Comment by scott-dt** [comment]
0.10.0 版 ios 尚未修復
