### ISSUE TITLE
ios 13.7 iphone 6s plus 上方多出一塊白色方塊

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#289]
## Description

ios 13.7 iphone 6s plus  capture & postcapture  & capture detail 頁面上方多出一塊白色方塊
![File](https://user-images.githubusercontent.com/62582260/101136295-17d03b80-3648-11eb-8d36-ba6f6a6ffc8f.jpg)

## Environment

- Version: 0.9.3
- OS:  iOS 13.7
- Device: iphone 6s

**Comment by CS6** [comment]
@scott-dt   iphone 6 plus   iphone 7 plus  iphone 8 plus 
只要為 ios 5.5 寸  約為 414 x 736 皆會有此狀況，這是為了對應 ios**瀏海** 所做的功能，
我會嘗試能不能判斷出這幾個機型，但只要有接近的機型具有 **瀏海** 這個issue 就可能修不了 😂

**Comment by seanwu1105** [comment]
@CS6 [The `safe-area-inset-top` might help](https://stackoverflow.com/questions/48044636/ionic-iphone-x-safe-areas-not-working-properly).

**Comment by CS6** [comment]
@seanwu1105  感謝，我會試試看效果如何 👍

**Comment by CS6** [comment]
fix
![image](https://user-images.githubusercontent.com/16307922/101344932-4573e980-38c1-11eb-9384-a0adfdb3f2c6.png)
![image](https://user-images.githubusercontent.com/16307922/101345080-7bb16900-38c1-11eb-9ef3-8e2d0a62b3b8.png)
