### ISSUE TITLE
Postcapture 有顯示上限 ( note20 顯示21 張 第22張無法顯示在 postcapture 頁面 )

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#291]
## Description

Postcapture 有顯示上限 ( note20 顯示21 張 第22張無法顯示在 postcapture 頁面 )
之後的可以接收 但不會顯示在 postcapture 頁面

## Environment

- Version: 0.9.4
- OS:  Android 10
- Device: samsung note20

**Comment by seanwu1105** [comment]
Virtual scrolling might help: https://material.angular.io/cdk/scrolling/overview

**Comment by scott-dt** [comment]
目前僅顯示最新的 10 張 postcapture
