### ISSUE TITLE
在未等待capture 頁面出現照片時接著繼續拍攝 會有順序顛倒的現象 

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#292]
在未等待capture 頁面出現罩便時接著繼續拍攝 會有順序顛倒的現象  
期望顯示會依照拍照順序排列
目前的狀況
![Screenshot_20201204-182133_Capture](https://user-images.githubusercontent.com/62582260/101155400-098f1900-3662-11eb-9234-c3763be515c9.jpg)

**Comment by seanwu1105** [comment]
This issue can be solved automatically after we implement the new uploading flow #212.

> Sean Wu Dec 4th at 6:26 PM
> @Scott Yan 是的喔，目前只有針對日期排序，如果不符合使用者期待，需要開一個新的 FR
> 
> Tammy  4 days ago
> @Scott Yan 請開一個 issue，因為一般的照片 app 不會出現顛倒的狀態，所以不算 FR，還是要算 issue 比較合適 (edited) 
> 
> Tammy  4 minutes ago
> @Sean Wu 這個 sprint 的 issue 是針對這個 comment 來的，所以只要是針對 時間 而不是 日期 ，就完成了。
> 
> Sean Wu  3 minutes ago
> @Tammy 好，那應該是我 comment 錯了抱歉抱歉 :cry: 那個時候還沒有認真研究為什麼排序不對，現在發現其實並非是日期的關係，而是上傳時間不同。
> 
> Tammy  1 minute ago
> ok 沒問題，總之是按照時間即可，至於資訊的內容來源是未來的事，之後再討論是否要修正即可
