### ISSUE TITLE
Can share PostCapture to other social media with watermark

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#311]
## Concept
Can share PostCapture to other social media with watermark

**Comment by wcchung** [comment]
sherry  17:17
@Tammy 我剛剛試了一 run, 目前會異常的有
1. ig -> 出現 error 無法傳送
2. wechat -> 出現 error 無法傳送
3. Slack -> 可分享但沒有照片
其餘的存下圖片、LINE、Signal、fb messenger…..都正常。

待 @scott-dt 補充 fb 分享狀況

**Comment by scott-dt** [comment]
兩個狀況 issue #381 
1. tammy 測試 按下 分享按鈕沒有反應
2. scott note 20 分享至 fb po 文週五下午約2點分享 完後沒有任何反應 直到周日清晨5 點突然出現在fb上
