### ISSUE TITLE
連續拍攝的狀況下會有相片沒存下來的狀況

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#329]
## Description
ios 13.7 iphone 7  : 只有最後一張會成功 前面9 張全部沒有存下來 ( 20 張只存下兩張 )
htc 1s : 20張發生兩張沒有存下來
note 20 : 目前測試20 張都沒發生沒有存下來的狀況
## Steps to Reproduce
1. 開啟app
2. 點選右下角 "相機 icon " 
3.進入相機模式
4. 按下快門 
5. 點選 " 確認 " 
6. 接著步驟 2 ~ 5 連續10次
7.是否於 capture 頁面 顯示剛剛拍攝的相片

## Environment

- Version: 0.11.4
- OS: Android 8.1.0 , Android 10 , ios 13.7
- Device: HTC EXODUS 1s , samsung note20 , iphone 7

**Comment by seanwu1105** [comment]
In Android, this is due to an upstream bug: https://github.com/ionic-team/capacitor/issues/3062.
