### ISSUE TITLE
按下拒絕後 會消失在 inbox 但是雙方的 activity 頁面還是顯示 in progress 而非 returned

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#334]
## Description
inbox 中按下 " 忽略 " 後 postcapture 會消失在 inbox , 但是雙方的 activity 頁面還是顯示 in progress 而非 returned

## Expected Behavior
- Expected: 當被按下忽略後雙方的 activity 頁面顯示 returned
- Actual: 當被按下忽略後雙方的 activity 頁面顯示 in progress 而非 returned

## Environment
- Version: 0.11.4
- OS: Android 8.1.0 ,Android 10  , iOS 13.7
- Device: HTC Exodus 1s ,samsung note20 , iphone 7

**Comment by scott-dt** [comment]
目前確定會呈現 等待 於 72 hr 後退回狀態才會改變

**Comment by tammyyang** [comment]
送回處理時也是 in progress，所以此 issue 不存在
可以額外開 request 讓說明便清晰
