### ISSUE TITLE
第一次升級後 sync 時加上說明

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#363]
## Description

第一次升級 ( 0.7.5 升級 ) 後 sync 時間會顯示空白等待， 加上說明提示

**Comment by wcchung** [comment]
建議說明文字 (From Tammy)

Syncing of your photo assets is in progress, this might take a few minutes. Please keep the app open and connected online.
正在同步您的影像資產至手機，這個步驟會執行數分鐘，請保持 app 開啟並且連線至網路。
