### ISSUE TITLE
照片沒有正常存入時會出現未知的錯誤（如圖），UX 體驗較差，建議改為簡單敘述如: 操作失敗請重新操作

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#366]
## Description
照片沒有正常存入時會出現未知的錯誤（如圖），UX 體驗較差，建議改為簡單敘述如: 操作失敗請重新操作
![Image from iOS](https://user-images.githubusercontent.com/62582260/102308882-872c2080-3fa2-11eb-8eae-99cd31256922.png)

**Comment by wcchung** [comment]
建議顯示訊息文字 (From Tammy)

Fail to register the asset. Please try again later.

**Comment by scott-dt** [comment]
20210126 beta 9 流程有做修改 此問題於先前版本為上傳註冊失敗時才會發生 目前整體流程修正後 會判斷是否有網路 若無網路哲暫停上傳 因此此問題目前尚未發生 需再觀察 2 個 sprint
