### ISSUE TITLE
iphone SE 上的 Empty Inbox 太靠近上方

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#371]
## Description
iphone SE 上的 Empty Inbox 太靠近上方
![Image from iOS](https://user-images.githubusercontent.com/62582260/102311044-20f5cc80-3fa7-11eb-87be-e0a7c7a2c4d9.png)

## Environment

- Version: 0.11.7
- OS: Android 7.1.1, iOS 14.1
- Device: HTC U11 , iphone SE

**Comment by wcchung** [comment]
Issue still exist in iPhone SE & Htc Exodus 1s

**Comment by wcchung** [comment]
Temporarily move to beta 8.2 (cc @scott-dt )

**Comment by scott-dt** [comment]
0.12.2 確認 1s & iphone 7 已修正
