### ISSUE TITLE
capture app 在於 Android 7.1.1 版本 安裝0.11.7 拍照會顯示 error 無法紀錄相片

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#372]
## Description

capture app 在於 Android 7.1.1 版本 安裝0.11.7 拍照會顯示 error 無法紀錄相片
![20201216_141150](https://user-images.githubusercontent.com/62582260/102312957-a0d16600-3faa-11eb-97cd-538d19b292cc.jpg)

## Environment

- Version: 0.11.7
- OS: Android 7.1.1
- Device:  HTC U11

**Comment by tammyyang** [comment]
目前沒有觀察到 error, closed
