### ISSUE TITLE
英文版本 所有系統相關的顯示 (非 app 的 i18n) 都會變成中文

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#380]
## Description
英文版本 所有系統相關的顯示 (非 app 的 i18n) 都會變成中文

## Steps to Reproduce
1. Open app
2. Open camera
3. See chinese characters

## Environment
- Version: 0.12.1 ( 0.7.5 即有此狀況發生 #238 )
- OS: Android , iOS
- Device: HTC Exodus 1s , note20 , iphone

**Comment by scott-dt** [comment]
samsung note 20 
![Screenshot_20201221-133808_Settings](https://user-images.githubusercontent.com/62582260/102743228-fe422a00-4391-11eb-9557-6a7a4100d2d7.jpg)

**Comment by tammyyang** [comment]
機型：Galaxy A42 5G
Android 10

**Comment by scott-dt** [comment]
0.12.2 完成修正
