### ISSUE TITLE
UI update: Add photo view/series view

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#394]
## Concept
UI update: Add photo view/series view 

## QA test

1. Go to Asset page
2. Can switch between Photo View and Series View
3. All PostCapture can be seen in the Photo View
4. Can see one mockup series in the Series View
5. [Optional] Click on the mockup series in the Series View, can go to Collection Status page
6. [Optional] Can see collection status with mockup data in the Collection Status page

**Comment by tammyyang** [comment]
Draft of the UI (尚未定版，可能會有視覺或設計差異)
![Uploading Screenshot 2021-03-05 163329.png…]()
