### ISSUE TITLE
Notification 如果是系統或行銷訊息，目前的 limitation 是只能顯示英文

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#398]
## Description
Notification 如果是系統或行銷訊息，例如「有個新功能出來囉！快更新吧」、「今天 0:00-6:00 系統更新暫停使用」，目前的 limitation 是只能顯示英文，這是之後會再修正

**Comment by shc261392** [comment]
因為目前 App 已加入自動向 backend 提供語言資料的功能，此 limitation 已經不存在
但目前 backend 缺少可以發送系統和行銷訊息的指令（new feature request for backend）

**Comment by scott-dt** [comment]
0.12.1 有接收到伺服器維修訊息
