### ISSUE TITLE
Authmedia 上不定時會出現相同照片重複上傳的狀況。

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#403]
## Description
拍照、上傳、若有剛剛拍的沒上傳完畢的按一下驚嘆號上傳。(測試穩定度)
照片沒有掉，但在 Authmedia 上不定時會出現相同照片重複上傳的狀況。時間差距大約 5~6s

## Environment

- Version: 0.12.1

**Comment by wcchung** [comment]
related to https://github.com/numbersprotocol/storage-backend/issues/130
