### ISSUE TITLE
直拍圖片點選 detail 時很常出現切割不當的狀況（期望: 100% 長寬 fit）

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#503]
## Description
直拍圖片點選 detail 時很常出現切割不當的狀況（期望: 100% 長寬 fit）

**Comment by seanwu1105** [comment]
This should have been fixed with https://github.com/numbersprotocol/capture-lite/commit/ab55748b0da8ef84fe4050312de6b0a1b46cffa3#diff-7c92d18396329d92133156d7e86db19bf096e335b2359677262129a704af788a. However, it still need to be verified on iOS devices.
