### ISSUE TITLE
 tutorial page 修正

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#516]
## Description
~~1. 相機icon ( 換成實心 ) page 1 ,2,3~~
2. 記錄當下 中文偏移 page 1
~~3.  share ,delete 背景色修正為 白色~~
4. 中文顯示時 範例圖示為英文 page 3

**Comment by scott-dt** [comment]
20210204 beta 11 測試 conditional pass 
項目 1 & 3  以完成

**Comment by seanwu1105** [comment]
@scott-dt 小技巧（？）如果輸入

```
- [ ] item
- [x] completed item
```

GitHub 會幫你轉換成 check list 並且會在 issues 中顯示進度。

**Comment by scott-dt** [comment]
beta 12 ui 有修正需要在做更新
