### ISSUE TITLE
ios下方bar 的 button 稍微高一點

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#517]
## Concept
將下方bar , button 稍微高一點，避開虛擬 HOME (其實他不叫 home 了）的位置
![Image from iOS](https://user-images.githubusercontent.com/62582260/106543342-7b8bbd80-6540-11eb-90c6-6a5e42d95435.jpg)

**Comment by wcchung** [comment]
可參考 ig
![Image from iOS (2)](https://user-images.githubusercontent.com/12252921/106544326-497b5b00-6542-11eb-9ac2-d29ef78fc125.jpg)
