### ISSUE TITLE
Grid UI of PostCapture (app)

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#542]
Grid UI of PostCapture (app)

**Comment by tammyyang** [comment]
![Uploading Screenshot 2021-03-02 145346.png…]()

**Comment by tammyyang** [comment]
![Screenshot 2021-03-02 162427](https://user-images.githubusercontent.com/5687908/109619478-cadf0100-7b73-11eb-980a-0db92e6b84bb.png)
基於目前的 Capture 新增與修改紅框部分

1. 在 Capture 頁面加入上方的 profile 資訊並且可以修改
2. 下方 icon 調整為兩個 (暫時看不見 PostCapture)

測試流程

1. 進入 Capture 頁面
2. 秀出所有 assets (s) & Profile 資訊
3. 點選新增 profile pic
4. 上傳一張 profile pic 
5. 回到 Capture 頁面 
6. 點選修改用戶名稱 
7. 修改用戶名稱
8. 回到 Capture 頁面，可看到修改的資訊都正確顯示

**Comment by scott-dt** [comment]
https://docs.google.com/presentation/d/1lnXs-dMzKT7IiAce4GdE9KLxohg2SFAWdlb-x0yaxtE/edit#slide=id.gc2f3ae0bfb_0_10

**Comment by scott-dt** [comment]
21.03.09 release tab 順序尚未解決 其餘通過測試

**Comment by scott-dt** [comment]
21.03.16 beta 13.1 tab 順序 修正完成
