### ISSUE TITLE
capture app 於特定機型 無法開啟app

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#553]
## Description
安裝app 後無法開啟 app
機型 : HTC U Ultra
Android 8.0.0

**Comment by seanwu1105** [comment]
This error will only occur on Android Oreo (8.0.0 API 26). For further details and the possible solution, please check [this answer](https://stackoverflow.com/a/50832408/8789738).

**Comment by seanwu1105** [comment]
Fix with f450008ef770d4f0e112a2097a3ed2d1216be4e2.

**Comment by scott-dt** [comment]
0.29.1 HTC U Ultra 已可正常使用
