### ISSUE TITLE
Launch open beta of Capture Lite in Android platforms

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#74]
## Android

- [x] Generate key pair with KeyStore @seanwu1105 @CS6 
- [x] Preserve the generated key pair @seanwu1105 @CS6 
- [x] Require a Google Play Console (Numbers) official account @wcchung

**Comment by wcchung** [comment]
Copy from Slack

--
DaYuan:house_with_garden:  18:12
現在是有工具可以修改產出基本的html，但是沒有地方可以放（外部連結）
看要不要先用之前的 bubble Mylog 頁面複製來改(替換html的部分為修改後的)
18:14
理論上要讓工具本身是個 SSR 服務才能做到修改後自動發布以供外部連結存取
18:14
不然還是得手動部署一個靜態頁面

sherry  18:18
@DaYuan 對不起…..我看不太懂 >“<
我們應該可以先把目前新產生的 license page，藏到 Numbers 的官網裡，這樣就有一個外部連結了 (跟先前 MyLog 一樣的做法)。目前 Numbers website 開發在 @Tammy 手上，是不是可以請 @Tammy or @Scott Yan 協助 (上次 MyLog 是 Scott 處理的)

DaYuan:house_with_garden:  18:19
白話文：目前工具不等於頁面，只能提供內容
解法：先跟上次一樣，我再提供內容給@Tammy or @Scott Yan 換

**Comment by scott-dt** [comment]
11/14  已上架 0.7.4
