### ISSUE TITLE
Slow performance in Capture page on Exodus 1 while loading the Capture App with more than 150 photos and 5 videos (loading of Camera button is also very slow)

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#748]
## Description
Slow performance in Capture page on Exodus 1 while loading the Capture App with more than 150 photos and 5 videos (loading of Camera button is also very slow)

**Comment by shc261392** [comment]
Performance observation on iOS

### Action: click on Capture and return to home page

<img width="767" alt="截圖 2021-06-23 下午2 27 21" src="https://user-images.githubusercontent.com/24616552/123046910-3c96cf80-d42f-11eb-929f-b7e5a2a90047.png">

JavaScript parts 

### Action: Taking a Capture

<img width="767" alt="截圖 2021-06-23 下午2 27 42" src="https://user-images.githubusercontent.com/24616552/123046916-3dc7fc80-d42f-11eb-9807-45bfc1dc64d2.png">

### Action: Uploading a Capture

<img width="767" alt="截圖 2021-06-23 下午2 27 51" src="https://user-images.githubusercontent.com/24616552/123046913-3d2f6600-d42f-11eb-855f-8fd2dd68d39a.png">
