### ISSUE TITLE
Send user token to CC when open CaptureClub from App

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#780]
Send user token to CC when open CaptureClub from App 
P.S: 像是 Authmedia 的方式 點擊 APP 後連結開啟的 CC 會自動登入顯示

備註 : 本次 qa 測試因 CC 尚未支援此功能 需至網址部分確認是否取得正確 TOKEN

**Comment by shc261392** [comment]
URLs

Home page: `https://captureclub.cc/?token=<token>`

Details page: `https://captureclub.cc/asset?mid=<mid>&token=<token>`

**Comment by scott-dt** [comment]
210719 確認 
1. 購買來的 capture  更多動作中的 " view on CaptureClub " 網址會夾帶 token
2. 設定選項 CaptureClub 點選後網址會夾帶 token
