### ISSUE TITLE
Cannot Take New Photos After App Uses Up Android Device Memory

### ISSUE THREAD

**Issue by seanwu1105** [numbersprotocol/capture-lite#83]
After the app contains multiple proofs, the app will be killed when taking new photos due to insufficient memory. Thus, after the the app recreated by Android, users will find out that the app does not store the new photo. This issue could be mitigate after #46 is resolved but that is not a complete solution.

**Comment by scott-dt** [comment]
200907 拍攝30 張正常紀錄
