### ISSUE TITLE
Add "Network Application" page

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#896]
Add "Network Application" page
![capture!UNITO-UNDERSCORE!app!UNITO-UNDERSCORE!mockup!UNITO-UNDERSCORE!3](https://user-images.githubusercontent.com/62582260/134613182-d5eaed2d-4fca-4fa8-bec9-bb394967318c.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1201059741703320) by [Unito](https://www.unito.io)

**Comment by tammyyang** [comment]
Migrate to asana <> unito sync, close the issue.
