### ISSUE TITLE
Update color to the new brand theme

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#899]
Update color to the new brand the
![image (4)](https://user-images.githubusercontent.com/62582260/134613331-425caa35-6903-40f8-97ab-a019a37dca5a.png)
![image (5)](https://user-images.githubusercontent.com/62582260/134613338-796a5bf6-5df8-47cc-a59f-e46e7852d645.png)
me

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1201059741808270) by [Unito](https://www.unito.io)

**Comment by tammyyang** [comment]
Migrate to asana <> unito sync, close the issue.
