### ISSUE TITLE
繁體中文尚未完成

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#91]
## Description
語系設定調整成中文點選後還顯示英文

## Steps to Reproduce

1. Go to 'setting' page
2. Click on 'languages'
3. Click on ' 繁體中文 '
依然顯示英文

## Expected Behavior

* Expected: 語系設定調整成中文點選後還顯示中文
* Actual: 語系設定調整成中文點選後還顯示英文

## Environment

* Version: 0.3.0
* OS:  Android 8
* Device: HTC Exodus 1s

**Comment by wcchung** [comment]
Copy From Slack

--------------------

Scott Yan  15:46
@Sean Wu @Tammy
capture lite beta3 測出來兩個問題
1. 在app 設定裡面的語系調成繁體中文後 沒有任何反應
2. 目前app 需要使用 tester@test.com 帳號上傳圖片 使用實習營帳號登入dashboard 才會顯示 使用其他帳號上傳 dashboard 不會顯示
以上兩個狀態目前是屬預期狀態?

Sean Wu  15:49
@Scott Yan 第一個是預期的，目前語言還沒有填入中文翻譯後的文字內容。第二個就現在@James 的設計應該不是預期的，不過問題可能不是發生在App。

**Comment by shc261392** [comment]
Current English translations: https://github.com/numbersprotocol/capture-lite/blob/develop/src/assets/i18n/en-us.json

zh-tw: https://github.com/numbersprotocol/capture-lite/blob/develop/src/assets/i18n/zh-tw.json

**Comment by shc261392** [comment]
@wcchung English translation has been updated on the latest `develop` branch. (34e4d58)

**Comment by shc261392** [comment]
https://docs.google.com/spreadsheets/d/1tC9YOFjozxjo77PhstFjyOO0O9wat17UqhaofeT_Poo/edit#gid=0

**Comment by scott-dt** [comment]
語系切換成中文 
1.上方的all , tags 為切換
2. 資訊欄內的文字為切換為中文
![Screenshot_20201013-170405](https://user-images.githubusercontent.com/62582260/95840007-3ca9e000-0d76-11eb-8c7c-9115f3190f06.png)
![Screenshot_20201013-170347](https://user-images.githubusercontent.com/62582260/95840019-3ddb0d00-0d76-11eb-8f17-c2016dcf46a7.png)

**Comment by scott-dt** [comment]
case 1 更新完成 
![Screenshot_20201014-113617_Capture Lite](https://user-images.githubusercontent.com/62582260/95940817-e1c5c680-0e11-11eb-97fb-9c42ab71c71f.jpg)

**Comment by scott-dt** [comment]
201014 sprint demo 討論資訊欄內的文字為收集當下手機資訊產生之資料 會依據當下手機與係設定為主要要收集與紀錄 如同拍照後人為紀錄一些資訊皆為當時使用之語言 後續再進行瀏覽觀看時應該呈現當時的狀態 不應隨著語系設定變換更改
