### ISSUE TITLE
Launch open beta of Capture Lite in iOS 

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#92]
- [x] Build in iOS 
- [x] Require an Apple (Numbers) official account 
- [x] Require an environment to build iOS 
- [x] Require an iPhone registered under the (Numbers) official account 
- [x] Implement the license page

**Comment by wcchung** [comment]
Copy from Slack

---------

tammy  16:38
16:39
@Scott Yan 但請你幫我加一個 issue 是 build iOS 版本 ，這次 release 我們可以先只放 Android，但我會需要盡快有 iOS 版本 (cc @Sean Wu) (edited

**Comment by scott-dt** [comment]
延至 下一個 milestone  tammy 提醒 hard due (11/18 當天要開放 beta 測試下載)

**Comment by scott-dt** [comment]
Implement the license page link:  https://numbersprotocol.io/version-test/privacypolicy?debug_mode=true

**Comment by scott-dt** [comment]
0.7.4 正在審查
